
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef ESP32XXX_H
#define ESP32XXX_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 esp32xxx_valueRangeTest (UNS8 typeValue, void * value);
const indextable * esp32xxx_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data esp32xxx_Data;
extern UNS32 input_data1;		/* Mapped at index 0x2000, subindex 0x01 */
extern UNS32 input_data2;		/* Mapped at index 0x2000, subindex 0x02 */
extern UNS32 input_data3;		/* Mapped at index 0x2000, subindex 0x03 */
extern UNS32 output_data1;		/* Mapped at index 0x2001, subindex 0x01 */
extern UNS32 output_data2;		/* Mapped at index 0x2001, subindex 0x02 */

#endif // ESP32XXX_H
