
/* File generated by gen_cfile.py. Should not be modified. */

#include "esp32xxx.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS32 input_data1 = 0x0;		/* Mapped at index 0x2000, subindex 0x01 */
UNS32 input_data2 = 0x0;		/* Mapped at index 0x2000, subindex 0x02 */
UNS32 input_data3 = 0x0;		/* Mapped at index 0x2000, subindex 0x03 */
UNS32 output_data1 = 0x0;		/* Mapped at index 0x2001, subindex 0x01 */
UNS32 output_data2 = 0x0;		/* Mapped at index 0x2001, subindex 0x02 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 esp32xxx_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 esp32xxx_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 esp32xxx_iam_a_slave = 1;

TIMER_HANDLE esp32xxx_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 esp32xxx_obj1000 = 0x0;	/* 0 */
                    subindex esp32xxx_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 esp32xxx_obj1001 = 0x0;	/* 0 */
                    subindex esp32xxx_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&esp32xxx_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 esp32xxx_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 esp32xxx_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex esp32xxx_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&esp32xxx_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 esp32xxx_obj1005 = 0x0;	/* 0 */
                    subindex esp32xxx_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1005, NULL }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 esp32xxx_obj1006 = 0x0;	/* 0 */
                    subindex esp32xxx_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1006, NULL }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 esp32xxx_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 esp32xxx_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 esp32xxx_obj1014 = 0x80;	/* 128 */
                    subindex esp32xxx_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1014, NULL }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 esp32xxx_highestSubIndex_obj1016 = 0;
                    UNS32 esp32xxx_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 esp32xxx_obj1017 = 0x3E8;	/* 1000 */
                    subindex esp32xxx_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&esp32xxx_obj1017, NULL }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 esp32xxx_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 esp32xxx_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 esp32xxx_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 esp32xxx_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 esp32xxx_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex esp32xxx_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&esp32xxx_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1018_Serial_Number, NULL }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 esp32xxx_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 esp32xxx_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 esp32xxx_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex esp32xxx_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&esp32xxx_highestSubIndex_obj1200, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1200_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1200_COB_ID_Server_to_Client_Transmit_SDO, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 esp32xxx_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 esp32xxx_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 esp32xxx_obj1400_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 esp32xxx_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 esp32xxx_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 esp32xxx_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 esp32xxx_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex esp32xxx_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&esp32xxx_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&esp32xxx_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&esp32xxx_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&esp32xxx_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&esp32xxx_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&esp32xxx_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 esp32xxx_highestSubIndex_obj1600 = 2; /* number of subindex - 1*/
                    UNS32 esp32xxx_obj1600[] = 
                    {
                      0x20010120,	/* 536936736 */
                      0x20010220	/* 536936992 */
                    };
                    subindex esp32xxx_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&esp32xxx_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1600[1], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 esp32xxx_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 esp32xxx_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 esp32xxx_obj1800_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 esp32xxx_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 esp32xxx_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 esp32xxx_obj1800_Event_Timer = 0x7D0;	/* 2000 */
                    UNS8 esp32xxx_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex esp32xxx_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&esp32xxx_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&esp32xxx_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&esp32xxx_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&esp32xxx_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&esp32xxx_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&esp32xxx_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 esp32xxx_highestSubIndex_obj1A00 = 3; /* number of subindex - 1*/
                    UNS32 esp32xxx_obj1A00[] = 
                    {
                      0x20000120,	/* 536871200 */
                      0x20000220,	/* 536871456 */
                      0x20000320	/* 536871712 */
                    };
                    subindex esp32xxx_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&esp32xxx_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1A00[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&esp32xxx_obj1A00[2], NULL }
                     };

/* index 0x2000 :   Mapped variable input */
                    UNS8 esp32xxx_highestSubIndex_obj2000 = 3; /* number of subindex - 1*/
                    subindex esp32xxx_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&esp32xxx_highestSubIndex_obj2000, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&input_data1, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&input_data2, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&input_data3, NULL }
                     };

/* index 0x2001 :   Mapped variable output */
                    UNS8 esp32xxx_highestSubIndex_obj2001 = 2; /* number of subindex - 1*/
                    subindex esp32xxx_Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&esp32xxx_highestSubIndex_obj2001, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&output_data1, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&output_data2, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable esp32xxx_objdict[] = 
{
  { (subindex*)esp32xxx_Index1000,sizeof(esp32xxx_Index1000)/sizeof(esp32xxx_Index1000[0]), 0x1000},
  { (subindex*)esp32xxx_Index1001,sizeof(esp32xxx_Index1001)/sizeof(esp32xxx_Index1001[0]), 0x1001},
  { (subindex*)esp32xxx_Index1005,sizeof(esp32xxx_Index1005)/sizeof(esp32xxx_Index1005[0]), 0x1005},
  { (subindex*)esp32xxx_Index1006,sizeof(esp32xxx_Index1006)/sizeof(esp32xxx_Index1006[0]), 0x1006},
  { (subindex*)esp32xxx_Index1014,sizeof(esp32xxx_Index1014)/sizeof(esp32xxx_Index1014[0]), 0x1014},
  { (subindex*)esp32xxx_Index1017,sizeof(esp32xxx_Index1017)/sizeof(esp32xxx_Index1017[0]), 0x1017},
  { (subindex*)esp32xxx_Index1018,sizeof(esp32xxx_Index1018)/sizeof(esp32xxx_Index1018[0]), 0x1018},
  { (subindex*)esp32xxx_Index1200,sizeof(esp32xxx_Index1200)/sizeof(esp32xxx_Index1200[0]), 0x1200},
  { (subindex*)esp32xxx_Index1400,sizeof(esp32xxx_Index1400)/sizeof(esp32xxx_Index1400[0]), 0x1400},
  { (subindex*)esp32xxx_Index1600,sizeof(esp32xxx_Index1600)/sizeof(esp32xxx_Index1600[0]), 0x1600},
  { (subindex*)esp32xxx_Index1800,sizeof(esp32xxx_Index1800)/sizeof(esp32xxx_Index1800[0]), 0x1800},
  { (subindex*)esp32xxx_Index1A00,sizeof(esp32xxx_Index1A00)/sizeof(esp32xxx_Index1A00[0]), 0x1A00},
  { (subindex*)esp32xxx_Index2000,sizeof(esp32xxx_Index2000)/sizeof(esp32xxx_Index2000[0]), 0x2000},
  { (subindex*)esp32xxx_Index2001,sizeof(esp32xxx_Index2001)/sizeof(esp32xxx_Index2001[0]), 0x2001},
};

const indextable * esp32xxx_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;break;
		case 0x1006: i = 3;break;
		case 0x1014: i = 4;break;
		case 0x1017: i = 5;break;
		case 0x1018: i = 6;break;
		case 0x1200: i = 7;break;
		case 0x1400: i = 8;break;
		case 0x1600: i = 9;break;
		case 0x1800: i = 10;break;
		case 0x1A00: i = 11;break;
		case 0x2000: i = 12;break;
		case 0x2001: i = 13;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &esp32xxx_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status esp32xxx_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index esp32xxx_firstIndex = {
  7, /* SDO_SVR */
  0, /* SDO_CLT */
  8, /* PDO_RCV */
  9, /* PDO_RCV_MAP */
  10, /* PDO_TRS */
  11 /* PDO_TRS_MAP */
};

const quick_index esp32xxx_lastIndex = {
  7, /* SDO_SVR */
  0, /* SDO_CLT */
  8, /* PDO_RCV */
  9, /* PDO_RCV_MAP */
  10, /* PDO_TRS */
  11 /* PDO_TRS_MAP */
};

const UNS16 esp32xxx_ObjdictSize = sizeof(esp32xxx_objdict)/sizeof(esp32xxx_objdict[0]); 

CO_Data esp32xxx_Data = CANOPEN_NODE_DATA_INITIALIZER(esp32xxx);

